date:
	g++ -o date date.cpp -std=c++11
function:
	g++ -o function function.cpp -std=c++11
io:
	g++ -o io input_output.cpp -std=c++11
operators:
	g++ -o operators operators.cpp -std=c++11
exception:
	g++ -o exception exception.cpp -std=c++11
