algorithms:
	g++ -o algorithms algorithms.cpp -std=c++11
class_sort_string:
	g++ -o class_sort_string class_sort_string.cpp -std=c++11
class_person:
	g++ -o class_person class_person.cpp -std=c++11
class_reverse:
	g++ -o class_reverse class_reverse.cpp -std=c++11