factorial:
	g++ -o factorial factorial.cpp -std=c++11

palindrom:
	g++ -o palindrom palindrom.cpp -std=c++11

const:
	g++ -o const const.cpp -std=c++11

vector:
	g++ -o vector vector.cpp -std=c++11

map:
	g++ -o map map.cpp -std=c++11

anograms:
	g++ -o anograms anograms.cpp -std=c++11